### ISSUE TITLE
New API will be released soon

### ISSUE THREAD

**Issue by xnekv03** [cypcz/nameday-api#1]
Jakube, could you please update your client so it's ready for new API version?
Specification is here https://app.swaggerhub.com/apis/nekvapil/InternationalNamedayAPI/3.0.0

final URL when released will remain the same https://api.abalin.net
~~https://apibeta.abalin.net~~ will be discontinued when I go live

**Comment by jkb-kt** [comment]
@xnekv03 yes, I will address this asap.

**Comment by jkb-kt** [comment]
Fixed in ef74111c6b9d37a518be4b7928fa51bd3fc8555d.
